prepare_satellite_data:
  classes: # Классы для сегментации
  - [building, 255] # [имя класса, интенсивность маски]
  - [road, 204]
  data_dir: data/satellite
  max_workers: 4
  zoom: 17 # zoom 17 соответствует примерно 1 px / m
  num_tiles: 5 # число тайлов по ширине и высоте изображения
  tile_size: 256 # размер тайла в пикселях
  dataset_dir: data/dataset
  map_box: ## Координаты, ограничивающие выбранную область
  - 37.51076 # min_lon
  - 55.65512 # min_lat
  - 37.58114 # max_lon
  - 55.69133 # max_lat
  osm: data/map.osm.pbf
  sources: ## TMS сервисы
    google: "http://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"
    bing: "http://a0.ortho.tiles.virtualearth.net/tiles/a{}.jpeg?g=2"
    arcgis: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    yandex: "https://sat04.maps.yandex.net/tiles?l=sat&x={x}&y={y}&z={z}"

prepare_dataset:
  satellite_dir: data/satellite/17
  dataset_dir: data/dataset
  max_workers: 4
  num_tiles: ${prepare_satellite_data.num_tiles}
  tile_size: ${prepare_satellite_data.tile_size}
  classes: ${prepare_satellite_data.classes}
  zoom: ${prepare_satellite_data.zoom}

training:
  random_seed: 42
  logs_dir: data/logs
  classes: ${prepare_satellite_data.classes}
  num_epoch: 5
  loader:
    dataset_dir: ${prepare_dataset.dataset_dir}
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    batch_size: 1
    num_workers: 4
    image_size: 256
  model:
    loss: 'mIoU' # доступные значения: ['Lovasz', 'Focal', 'mIoU', 'CrossEntropy']
    metric: 'mcc' # доступные метрики: ['miou', 'fg_iou', 'mcc']
    cuda: true
    num_classes: 3
    opt:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1e-08
      weight_decay: 0.01
    sch:
      num_epoch: ${training.num_epoch}
      eta_min: 1e-6

eval:
  classes: ${prepare_satellite_data.classes}
  checkpoint_path: ${training.logs_dir}/DvcLiveLogger/model_training/checkpoints/epoch=4-step=1750.ckpt
  data_in: data/satellite/17/79198/41015/yandex.jpg
  data_out: data/predict/
  image_size: ${training.loader.image_size}
  model: ${training.model}
